//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }

        public virtual SteamVR_Action_Pose EyeGaze
        {
            get
            {
                return SteamVR_Actions.default_EyeGaze;
            }
        }

        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Joystick
        {
            get
            {
                return SteamVR_Actions.default_Joystick;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Button
        {
            get
            {
                return SteamVR_Actions.default_B_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Button
        {
            get
            {
                return SteamVR_Actions.default_A_Button;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoyStickClick
        {
            get
            {
                return SteamVR_Actions.default_JoyStickClick;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPad
        {
            get
            {
                return SteamVR_Actions.default_TrackPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean System
        {
            get
            {
                return SteamVR_Actions.default_System;
            }
        }
        
        public virtual SteamVR_Action_Single HandTrigger
        {
            get
            {
                return SteamVR_Actions.default_HandTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackPadTouched
        {
            get
            {
                return SteamVR_Actions.default_TrackPadTouched;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Touch
        {
            get
            {
                return SteamVR_Actions.default_A_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Touch
        {
            get
            {
                return SteamVR_Actions.default_B_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickTouch
        {
            get
            {
                return SteamVR_Actions.default_JoystickTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.default_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbrestTouch
        {
            get
            {
                return SteamVR_Actions.default_ThumbrestTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
