//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_Pose;

        private static SteamVR_Action_Pose p_default_EyeGaze;

        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Vector2 p_default_Joystick;
        
        private static SteamVR_Action_Boolean p_default_B_Button;
        
        private static SteamVR_Action_Boolean p_default_A_Button;
        
        private static SteamVR_Action_Single p_default_Trigger;
        
        private static SteamVR_Action_Boolean p_default_JoyStickClick;
        
        private static SteamVR_Action_Vector2 p_default_TrackPad;
        
        private static SteamVR_Action_Boolean p_default_System;
        
        private static SteamVR_Action_Single p_default_HandTrigger;
        
        private static SteamVR_Action_Boolean p_default_TrackPadTouched;
        
        private static SteamVR_Action_Boolean p_default_A_Touch;
        
        private static SteamVR_Action_Boolean p_default_B_Touch;
        
        private static SteamVR_Action_Boolean p_default_JoystickTouch;
        
        private static SteamVR_Action_Boolean p_default_TriggerTouch;
        
        private static SteamVR_Action_Boolean p_default_ThumbrestTouch;
        
        private static SteamVR_Action_Boolean p_default_Grip;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }

        public static SteamVR_Action_Pose default_EyeGaze
        {
            get
            {
                return SteamVR_Actions.p_default_EyeGaze.GetCopy<SteamVR_Action_Pose>();
            }
        }

        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_Joystick
        {
            get
            {
                return SteamVR_Actions.p_default_Joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_B_Button
        {
            get
            {
                return SteamVR_Actions.p_default_B_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_A_Button
        {
            get
            {
                return SteamVR_Actions.p_default_A_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single default_Trigger
        {
            get
            {
                return SteamVR_Actions.p_default_Trigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_JoyStickClick
        {
            get
            {
                return SteamVR_Actions.p_default_JoyStickClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_TrackPad
        {
            get
            {
                return SteamVR_Actions.p_default_TrackPad.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_System
        {
            get
            {
                return SteamVR_Actions.p_default_System.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single default_HandTrigger
        {
            get
            {
                return SteamVR_Actions.p_default_HandTrigger.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TrackPadTouched
        {
            get
            {
                return SteamVR_Actions.p_default_TrackPadTouched.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_A_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_A_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_B_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_B_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_JoystickTouch
        {
            get
            {
                return SteamVR_Actions.p_default_JoystickTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TriggerTouch
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ThumbrestTouch
        {
            get
            {
                return SteamVR_Actions.p_default_ThumbrestTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Grip
        {
            get
            {
                return SteamVR_Actions.p_default_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_EyeGaze,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Joystick,
                    SteamVR_Actions.default_B_Button,
                    SteamVR_Actions.default_A_Button,
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_JoyStickClick,
                    SteamVR_Actions.default_TrackPad,
                    SteamVR_Actions.default_System,
                    SteamVR_Actions.default_HandTrigger,
                    SteamVR_Actions.default_TrackPadTouched,
                    SteamVR_Actions.default_A_Touch,
                    SteamVR_Actions.default_B_Touch,
                    SteamVR_Actions.default_JoystickTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_ThumbrestTouch,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_EyeGaze,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_Joystick,
                    SteamVR_Actions.default_B_Button,
                    SteamVR_Actions.default_A_Button,
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_JoyStickClick,
                    SteamVR_Actions.default_TrackPad,
                    SteamVR_Actions.default_System,
                    SteamVR_Actions.default_HandTrigger,
                    SteamVR_Actions.default_TrackPadTouched,
                    SteamVR_Actions.default_A_Touch,
                    SteamVR_Actions.default_B_Touch,
                    SteamVR_Actions.default_JoystickTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_ThumbrestTouch,
                    SteamVR_Actions.default_Grip};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_EyeGaze};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_B_Button,
                    SteamVR_Actions.default_A_Button,
                    SteamVR_Actions.default_JoyStickClick,
                    SteamVR_Actions.default_System,
                    SteamVR_Actions.default_TrackPadTouched,
                    SteamVR_Actions.default_A_Touch,
                    SteamVR_Actions.default_B_Touch,
                    SteamVR_Actions.default_JoystickTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_ThumbrestTouch,
                    SteamVR_Actions.default_Grip};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_HandTrigger};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_Joystick,
                    SteamVR_Actions.default_TrackPad};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Joystick,
                    SteamVR_Actions.default_B_Button,
                    SteamVR_Actions.default_A_Button,
                    SteamVR_Actions.default_Trigger,
                    SteamVR_Actions.default_JoyStickClick,
                    SteamVR_Actions.default_TrackPad,
                    SteamVR_Actions.default_System,
                    SteamVR_Actions.default_HandTrigger,
                    SteamVR_Actions.default_TrackPadTouched,
                    SteamVR_Actions.default_A_Touch,
                    SteamVR_Actions.default_B_Touch,
                    SteamVR_Actions.default_JoystickTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_ThumbrestTouch,
                    SteamVR_Actions.default_Grip};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_EyeGaze = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/EyeGaze")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_Joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Joystick")));
            SteamVR_Actions.p_default_B_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/B-Button")));
            SteamVR_Actions.p_default_A_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/A_Button")));
            SteamVR_Actions.p_default_Trigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/Trigger")));
            SteamVR_Actions.p_default_JoyStickClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/JoyStickClick")));
            SteamVR_Actions.p_default_TrackPad = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/TrackPad")));
            SteamVR_Actions.p_default_System = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/System")));
            SteamVR_Actions.p_default_HandTrigger = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/HandTrigger")));
            SteamVR_Actions.p_default_TrackPadTouched = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TrackPadTouched")));
            SteamVR_Actions.p_default_A_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/A_Touch")));
            SteamVR_Actions.p_default_B_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/B_Touch")));
            SteamVR_Actions.p_default_JoystickTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/JoystickTouch")));
            SteamVR_Actions.p_default_TriggerTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TriggerTouch")));
            SteamVR_Actions.p_default_ThumbrestTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ThumbrestTouch")));
            SteamVR_Actions.p_default_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Grip")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
